### GET all users
GET localhost:8888/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZXhwIjoxNjM1ODQ3MjkwLCJpYXQiOjE2MzU4NDcxMTAsInJvbGUiOiJhZG1pbiJ9.QEhWdNvmHfjtTdVvVNdnRnvE_a5_4D3M8jg32_wOyBo

### GET user by ID
GET localhost:8888/api/users/5
Content-Type: application/json

### GET user by non-existing ID
GET localhost:8888/api/users/1
Content-Type: application/json

### GET non-existing path
GET localhost:8888/api/sdfsdfs
Content-Type: application/json

### check against a proper password
POST http://localhost:8888/api/login
Content-Type: application/json

{
  "email": "strelok@stalker.com",
  "password": "password123"
}

### check against an invalid password
POST http://localhost:8888/api/login
Content-Type: application/json

{
  "email": "strelok@stalker.com",
  "password": "thispasswordiswrong",
}

### check against a non-existing user
POST http://localhost:8888/api/login
Content-Type: application/json

{
  "email": "ztrelokz@stalker.com",
  "password": "thispasswordiswrong"
}

### register new user
POST http://localhost:8888/api/register
Content-Type: application/json

{
  "firstName": "Ivan",
  "lastName": "Sakharov",
  "phoneNumber": "111-11-111",
  "email": "sakharov2@science.ua",
  "password": "dada123"
}
